"""empty message

Revision ID: 837f609d7777
Revises: fe09c3011e42
Create Date: 2020-08-05 14:08:49.158578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837f609d7777'
down_revision = 'fe09c3011e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'university_degree',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'university_degree',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    # ### end Alembic commands ###
